<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="1" time="0.678"><testcase classname="test.index_test.S256Test" file="test/index_test.py" line="5" name="test_verify" time="0.0012853145599365234"><failure message="AssertionError: None is not true">self = &lt;index_test.S256Test testMethod=test_verify&gt;

    def test_verify(self):
        point = S256Point(
            0x887387e452b8eacc4acfde10d9aaf7f6d9a0f975aabb10d006e4da568744d06c,
            0x61de6d95231cd89026e286df3b6ae4a894a3378e393e93a0f45b666329a0ae34)
        z = 0xec208baa0fc1c19f708a9ca96fdeff3ac3f230bb4a7ba4aede4942ad003c0f60
        r = 0xac8d1c87e51d0d441be8b3dd5b05c8795b48875dffe00b7ffcfac23010d3a395
        s = 0x68342ceff8935ededd102dd876ffd6ba72d6a427a3edb13d26eb0781cb423c4
&gt;       self.assertTrue(point.verify(z, Signature(r, s)))
E       AssertionError: None is not true

test/index_test.py:13: AssertionError</failure></testcase></testsuite>